### ISSUE TITLE
[ master & surely others ] - Avatar  - Uploading Avatar from settings page

### ISSUE THREAD

**Issue by ELKAMINA** [ELKAMINA/42_transcendance#18]
Quand j'essaie d'uploader une image depuis la page Settings, la page ne se met pas a jour directement et un message d'erreur apparait cote client. "Cannot read property " status" '

**Comment by Alicia-bites** [comment]
error message : 
settings.tsx:67 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'status')
    at Socket.<anonymous> (settings.tsx:67:1)
    at Emitter.emit (index.mjs:136:1)
    at Socket.emitEvent (socket.js:498:1)
    at Socket.onevent (socket.js:485:1)
    at Socket.onpacket (socket.js:455:1)
    at Emitter.emit (index.mjs:136:1)
    at manager.js:204:1

**Comment by ELKAMINA** [comment]
Résolu.

liée à l'issue #78
